# Generated by Django 5.2.5 on 2025-08-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('airline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('star', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=100)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('insurance_included', models.BooleanField(default=False)),
                ('rich_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure_tour', to='tours.flightinfo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotel')),
                ('images', models.ManyToManyField(blank=True, to='tours.image')),
                ('itinerary', models.ManyToManyField(blank=True, to='tours.itineraryitem')),
                ('return_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_tour', to='tours.flightinfo')),
                ('services', models.ManyToManyField(blank=True, to='tours.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
