# Generated by Django 5.2.5 on 2025-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=12, upload_to='tours/images/'),
            preserve_default=False,
        ),
    ]
