# Generated by Django 5.2.5 on 2025-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_image_url_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('داخلی', 'داخلی'), ('خارجی', 'خارجی')], max_length=50, null=True),
        ),
    ]
