# Generated by Django 5.2.5 on 2025-08-26 16:45

import tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_destination_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=100)),
                ('destination_type', models.CharField(blank=True, choices=[('داخلی', 'داخلی'), ('خارجی', 'خارجی')], max_length=50, null=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('departure', models.JSONField(validators=[tours.models.validate_departure])),
                ('return_info', models.JSONField(validators=[tours.models.validate_return])),
                ('hotel', models.JSONField(validators=[tours.models.validate_hotel])),
                ('services', models.JSONField(default=list, validators=[tours.models.validate_services])),
                ('itinerary', models.JSONField(default=list, validators=[tours.models.validate_itinerary])),
                ('images', models.JSONField(default=list, validators=[tours.models.validate_images])),
                ('insurance_included', models.BooleanField(default=False)),
                ('rich_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
