# Generated by Django 5.2.5 on 2025-08-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tours.tour')),
            ],
        ),
        migrations.DeleteModel(
            name='Tour2',
        ),
    ]
