# Generated by Django 5.2.5 on 2025-08-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tourchunk_delete_tour2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourChunk',
            new_name='Chunk',
        ),
    ]
