# Generated by Django 5.2.5 on 2025-09-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(default='faq', max_length=50)),
                ('text', models.TextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tours.faq')),
            ],
        ),
        migrations.CreateModel(
            name='FAQChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tours.faqchunk')),
            ],
        ),
    ]
